footprint: [[0.7, -0.4], [0.7, 0.45], [-0.65, 0.45], [-0.65, -0.4]]

publish_frequency: 1.0

inflation_layer:
  inflation_radius: 0.4

obstacle_laser_layer:
  obstacle_range: 2.5
  raytrace_range: 5.5
  observation_sources: front_laser
  front_laser: 
    data_type: LaserScan
    topic: $(arg front_scan_topic)
    marking: true
    clearing: true

obstacle_camera_layer:
  obstacle_range: 2.5
  raytrace_range: 5.5
  observation_sources: front_rgbd_to_scan
  front_rgbd_to_scan:
    data_type: LaserScan
    topic: $(arg front_rgbd_to_scan_topic)
    marking: true
    clearing: true

temporal_3d_layer:
  plugin: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"
  enabled:                  true
  voxel_decay:              15.0  # seconds if linear, e^n if exponential
  decay_model:              0     # 0=linear, 1=exponential, -1=persistent
  voxel_size:               0.05  # meters
  track_unknown_space:      true  # default space is known
  mark_threshold:           0     # voxel height
  update_footprint_enabled: true
  combination_method:       1     # 1=max, 0=override
  origin_z:                 0.0   # meters
  publish_voxel_map:        false # default off
  transform_tolerance:      0.2   # seconds
  mapping_mode:             false # default off, saves map not for navigation
  map_save_duration:        60.0  # default 60s, how often to autosave
  observation_sources:      3d_laser_layer
  3d_laser_layer:
    data_type: PointCloud2
    topic: /robot/front_3d_laser/points_3d/filtered
    marking: true
    clearing: false
    obstacle_range: 3.0          # meters
    min_obstacle_height: 0.2     # default 0, meters
    max_obstacle_height: 2.0     # default 3, meters
    expected_update_rate: 0.0    # default 0, if not updating at this rate at least, remove from buffer
    observation_persistence: 0.0 # default 0, use all measurements taken during now-value, 0=latest
    inf_is_valid: false          # default false, for laser scans
    filter: "passthrough"        # default passthrough, apply "voxel", "passthrough", or no filter to sensor data, recommend on 
    voxel_min_points: 0          # default 0, minimum points per voxel for voxel filter
    clear_after_reading: true    # default false, clear the buffer after the layer gets readings from it
